// <auto-generated />
using System;
using FoodMatch.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FoodMatch.Infrastructure.Migrations
{
    [DbContext(typeof(FoodMatchDbContext))]
    [Migration("20260924131247_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FoodMatch.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MatchRequestId")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("SenderTempUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MatchRequestId");

                    b.HasIndex("SenderTempUserId");

                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("FoodMatch.Domain.Entities.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvgPriceRange")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("CuisineType")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MealTime")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("foods", (string)null);
                });

            modelBuilder.Entity("FoodMatch.Domain.Entities.FoodFoodTag", b =>
                {
                    b.Property<int>("FoodId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("FoodId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("food_food_tags", (string)null);
                });

            modelBuilder.Entity("FoodMatch.Domain.Entities.FoodSuggestionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FoodId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SuggestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SuggestionType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TempUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("TempUserId");

                    b.ToTable("food_suggestion_logs", (string)null);
                });

            modelBuilder.Entity("FoodMatch.Domain.Entities.FoodTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("food_tags", (string)null);
                });

            modelBuilder.Entity("FoodMatch.Domain.Entities.MatchRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FromTempUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ToTempUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FromTempUserId");

                    b.HasIndex("ToTempUserId");

                    b.ToTable("match_requests", (string)null);
                });

            modelBuilder.Entity("FoodMatch.Domain.Entities.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("ExternalPlaceId")
                        .HasColumnType("text");

                    b.Property<bool>("IsBuffet")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInMall")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double>("Lng")
                        .HasColumnType("double precision");

                    b.Property<string>("MallName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Lat", "Lng");

                    b.ToTable("restaurants", (string)null);
                });

            modelBuilder.Entity("FoodMatch.Domain.Entities.TempUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("CurrentLat")
                        .HasColumnType("double precision");

                    b.Property<double?>("CurrentLng")
                        .HasColumnType("double precision");

                    b.Property<string>("DesiredFood")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FoodPreferencesJson")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<bool>("LocationVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SessionToken");

                    b.HasIndex("CurrentLat", "CurrentLng");

                    b.ToTable("temp_users", (string)null);
                });

            modelBuilder.Entity("FoodMatch.Domain.Entities.UserReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ReportedTempUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReporterTempUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReportedTempUserId");

                    b.HasIndex("ReporterTempUserId");

                    b.ToTable("user_reports", (string)null);
                });

            modelBuilder.Entity("FoodMatch.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("FoodMatch.Domain.Entities.MatchRequest", "MatchRequest")
                        .WithMany("ChatMessages")
                        .HasForeignKey("MatchRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodMatch.Domain.Entities.TempUser", "SenderTempUser")
                        .WithMany("ChatMessages")
                        .HasForeignKey("SenderTempUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MatchRequest");

                    b.Navigation("SenderTempUser");
                });

            modelBuilder.Entity("FoodMatch.Domain.Entities.FoodFoodTag", b =>
                {
                    b.HasOne("FoodMatch.Domain.Entities.Food", "Food")
                        .WithMany("FoodFoodTags")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodMatch.Domain.Entities.FoodTag", "Tag")
                        .WithMany("FoodFoodTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("FoodMatch.Domain.Entities.FoodSuggestionLog", b =>
                {
                    b.HasOne("FoodMatch.Domain.Entities.Food", "Food")
                        .WithMany("SuggestionLogs")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodMatch.Domain.Entities.TempUser", "TempUser")
                        .WithMany("SuggestionLogs")
                        .HasForeignKey("TempUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Food");

                    b.Navigation("TempUser");
                });

            modelBuilder.Entity("FoodMatch.Domain.Entities.MatchRequest", b =>
                {
                    b.HasOne("FoodMatch.Domain.Entities.TempUser", "FromTempUser")
                        .WithMany("SentMatchRequests")
                        .HasForeignKey("FromTempUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoodMatch.Domain.Entities.TempUser", "ToTempUser")
                        .WithMany("ReceivedMatchRequests")
                        .HasForeignKey("ToTempUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromTempUser");

                    b.Navigation("ToTempUser");
                });

            modelBuilder.Entity("FoodMatch.Domain.Entities.UserReport", b =>
                {
                    b.HasOne("FoodMatch.Domain.Entities.TempUser", "ReportedTempUser")
                        .WithMany()
                        .HasForeignKey("ReportedTempUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoodMatch.Domain.Entities.TempUser", "ReporterTempUser")
                        .WithMany()
                        .HasForeignKey("ReporterTempUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReportedTempUser");

                    b.Navigation("ReporterTempUser");
                });

            modelBuilder.Entity("FoodMatch.Domain.Entities.Food", b =>
                {
                    b.Navigation("FoodFoodTags");

                    b.Navigation("SuggestionLogs");
                });

            modelBuilder.Entity("FoodMatch.Domain.Entities.FoodTag", b =>
                {
                    b.Navigation("FoodFoodTags");
                });

            modelBuilder.Entity("FoodMatch.Domain.Entities.MatchRequest", b =>
                {
                    b.Navigation("ChatMessages");
                });

            modelBuilder.Entity("FoodMatch.Domain.Entities.TempUser", b =>
                {
                    b.Navigation("ChatMessages");

                    b.Navigation("ReceivedMatchRequests");

                    b.Navigation("SentMatchRequests");

                    b.Navigation("SuggestionLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
